name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: ["pio","qio"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install qio
        if: matrix.package == 'qio'
        run: |
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install https://github.com/OS-Q/P17/archive/master.zip

      - name: Install pio
        if: matrix.package == 'pio'
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/P17/archive/master.zip

      - name: Build
        run: |
          pio run -d .
